### ISSUE TITLE
Fail with C1 22 on MacOS 12.3.1

### ISSUE THREAD

**Issue by Korsani** [walterrowe/add_border#1]
Hi,
At last I found something to show photos not in a collection...
But if fails here, with this message : 
Il est impossible d’obtenir «class COcl» "All Images" of document "GGW4" of application "Capture One 22".
Erreur dans Capture One 22 : Il est impossible d’obtenir collection "All Images" of document "GGW4". (-1728)

**Comment by walterrowe** [comment]
Thanks for reporting this. I need to know how were you invoking the script.

- Were you dropping images on it via Finder?
- Using it the Open with field of an an Export recipe?
- Did you add it to the Capture One Scripts folder?
- What file type were you sending to it?

I have used it on JPG files with no issues.

**Comment by walterrowe** [comment]
I tested today this on macOS 12.2.1 with no issues. Capture One does not officially support 12.3.x and I don't have a system upgraded to that version where I can test it.

**Comment by walterrowe** [comment]
See the article [What Capture One version will run on my machine?](https://support.captureone.com/hc/en-us/articles/360004526177-Which-Capture-One-version-will-run-on-my-machine-) on the Capture One website.

**Comment by walterrowe** [comment]
Did you mean to report this on the add_border project or another project?
